return {
    mesh = "games/nagashino/assets/models/battlefield",
    render = {
        skipSuffixes = { "_col", "_trigger" },
        skipNames = { "mud_charge_road" },
        skipPrefixes = { "teppo_smoke_" },
        colliderSuffix = "_col",
        triggerSuffix = "_trigger",
    },
    materials = {
        default = {
            albedo = "nagashino_grass_cc0_color",
            normal = "nagashino_grass_cc0_normal",
            roughnessMap = "nagashino_grass_cc0_roughness",
            aoMap = "nagashino_grass_cc0_ao",
            color = { 1, 1, 1, 1 },
            metallic = 0,
            roughness = 0.72,
            ao = 1,
            normalScale = 0.2,
        },
        grass_battlefield = {
            albedo = "nagashino_grass_cc0_color",
            normal = "nagashino_grass_cc0_normal",
            roughnessMap = "nagashino_grass_cc0_roughness",
            aoMap = "nagashino_grass_cc0_ao",
            color = { 0.78, 0.80, 0.72, 1 },
            metallic = 0,
            roughness = 0.86,
            ao = 1,
            normalScale = 0.25,
            receivesBattlefieldState = true,
        },
        mud_road = {
            albedo = "nagashino_mud_cc0_color",
            normal = "nagashino_mud_cc0_normal",
            roughnessMap = "nagashino_mud_cc0_roughness",
            aoMap = "nagashino_mud_cc0_ao",
            color = { 0.72, 0.68, 0.60, 1 },
            metallic = 0,
            roughness = 0.92,
            ao = 1,
            normalScale = 0.15,
            receivesBattlefieldState = true,
        },
        wood_dark = {
            albedo = "nagashino_wood",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 0.78, 0.58, 0.38, 1 },
            metallic = 0,
            roughness = 0.74,
            ao = 1,
            normalScale = 0.35,
        },
        tree_bark = {
            albedo = "nagashino_tree_bark_color",
            normal = "nagashino_tree_bark_normal",
            color = { 0.72, 0.62, 0.48, 1 },
            metallic = 0,
            roughness = 0.86,
            ao = 1,
            normalScale = 0.42,
        },
        tree_leaves = {
            albedo = "nagashino_tree_leaves_color",
            normal = "nagashino_tree_leaves_normal",
            alphaMask = "nagashino_tree_leaves_alpha",
            alphaCutoff = 0.32,
            color = { 0.74, 0.94, 0.61, 1 },
            metallic = 0,
            roughness = 0.92,
            ao = 1,
            normalScale = 0.34,
        },
        water_stream = {
            albedo = "nagashino_water",           -- 水面路径不采样 albedo，仅占位防止贴图状态残留
            normal = "nagashino_water_normal",    -- 程序化平铺波纹法线（tools/gen_textures.js）
            type = "water",
            flowDirection = { 1.0, 0.12 },
            shallowColor = { 0.11, 0.24, 0.20 },
            deepColor = { 0.012, 0.055, 0.085 },
            color = { 1, 1, 1, 1 },
            metallic = 0,
            roughness = 0.09,                     -- 低粗糙度 → 日光碎金闪点（太低会奶白爆点）
            ao = 1,
            normalScale = 0.30,                   -- 波纹强度（太高中景发"肥皂水"白）
        },
        foliage_dark = {
            albedo = "nagashino_leaves_color",
            normal = "nagashino_leaves_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 0.78, 0.92, 0.70, 1 },
            metallic = 0,
            roughness = 0.88,
            ao = 1,
            normalScale = 0.75,
        },
        foliage_light = {
            albedo = "nagashino_leaves_color",
            normal = "nagashino_leaves_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 1.02, 1.12, 0.86, 1 },
            metallic = 0,
            roughness = 0.85,
            ao = 1,
            normalScale = 0.75,
        },
        hill_earth = {
            albedo = "nagashino_rock_cc0_color",
            normal = "nagashino_rock_cc0_normal",
            roughnessMap = "nagashino_rock_cc0_roughness",
            aoMap = "nagashino_rock_cc0_ao",
            color = { 0.76, 0.80, 0.72, 1 },
            metallic = 0,
            roughness = 0.90,
            ao = 1,
            normalScale = 0.62,
            receivesBattlefieldState = true,
        },
        river_bank = {
            albedo = "nagashino_mud_cc0_color",
            normal = "nagashino_mud_cc0_normal",
            roughnessMap = "nagashino_mud_cc0_roughness",
            aoMap = "nagashino_mud_cc0_ao",
            color = { 0.62, 0.66, 0.58, 1 },
            metallic = 0,
            roughness = 0.92,
            ao = 1,
            normalScale = 0.75,
            receivesBattlefieldState = true,
        },
        gun_smoke = {
            albedo = "nagashino_smoke",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 0.8, 0.82, 0.78, 0.72 },
            metallic = 0,
            roughness = 0.96,
            ao = 1,
            normalScale = 0.05,
        },
        cloth_takeda = {
            albedo = "nagashino_cloth_takeda",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 1, 1, 1, 1 },
            metallic = 0,
            roughness = 0.64,
            ao = 1,
            normalScale = 0.2,
        },
        cloth_oda = {
            albedo = "nagashino_cloth_oda",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 1, 1, 1, 1 },
            metallic = 0,
            roughness = 0.62,
            ao = 1,
            normalScale = 0.2,
        },
        cloth_tokugawa = {
            albedo = "nagashino_cloth_tokugawa",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 1, 1, 1, 1 },
            metallic = 0,
            roughness = 0.62,
            ao = 1,
            normalScale = 0.2,
        },
        ashigaru_cloth = {
            albedo = "nagashino_cloth_oda",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 0.55, 0.58, 0.58, 1 },
            metallic = 0,
            roughness = 0.68,
            ao = 1,
            normalScale = 0.18,
        },
        takeda_armor = {
            albedo = "nagashino_cloth_takeda",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 0.9, 0.72, 0.68, 1 },
            metallic = 0.15,
            roughness = 0.48,
            ao = 1,
            normalScale = 0.18,
        },
        horse_brown = {
            albedo = "nagashino_mud",
            normal = "nagashino_flat_normal",
            pbr = "nagashino_neutral_pbr",
            color = { 0.65, 0.48, 0.32, 1 },
            metallic = 0,
            roughness = 0.70,
            ao = 1,
            normalScale = 0.16,
        },
    },
}
